<div class="page-header" filter-color="" >

    <div class="container" page-header>

        <div class="col-md-4 content-center">
            <div class="card card-sign card-plain"> 
                <form class="form" method="post" action="">
                    <div class="header header-primary text-center">
                        <div class="logo-container">

						 <H1 class="title"> BIENVENUE AU CLUB OTAKU  </H1> 
						
                        </div>
                    </div>    <br/> 
                    
                    


                </form>
            </div>
        </div>
    </div>
</div>
